### ISSUE TITLE
Lang

### ISSUE THREAD

**Issue by knapeto** [dozoisch/react-google-recaptcha#17]
Hey everyone,

how i set lang param for change language?

Thanks.

**Comment by dozoisch** [comment]
Hi, how is that done on normal recaptcha? I'm not sure I currently support it.

**Comment by invalidred** [comment]
Good to see someone interested in rendering a different language. 

Pretty much we need to "hl" attribute added in addition to other attributes.

https://developers.google.com/recaptcha/docs/display

Check the "JavaScript resource (api.js) parameters" section.

Is it possible to add language support to the component?

**Comment by invalidred** [comment]
i am willing to help out... hopefully i'll submit a pull request soon.

**Comment by dozoisch** [comment]
@invalidred awesome!

**Comment by invalidred** [comment]
@dozoisch this is much harder than i expected.

To render a different language we need to set it in the URL through "hl" query string param.

https://www.google.com/recaptcha/api.js?onload=${callbackName}&render=explicit&hl=${languageCodeGoesHere}

The URL is hardcoded and defined in recaptcha-wrapper.js file which uses the 'react-async-script' higher order component to load the script from google and then render the Recaptcha component.

So the problems and possible solutions are:

1) "hl" is a query param which is a part of url and not the recaptcha component itself, thus we can't just pass it to the component recaptch.js. Maybe we could :
    a) create a react component that accepts the same props as the Recaptcha component that accepts an additional "languageCode" prop and renders makeAsycnScriptLoader ('react-async-script'). This way is someone passes a languageCode we can change the url and call makeAsyncScriptLoaded higher order component with the correct URL

2)The other problem is what if the user changes the language (assuming they use the recaptcha component on a site that can dynamically change it's language) then I am not sure how to render the entire component (including loading a new script from google)

Could you please give me some direction/insight/feedback as there may be another way?

**Comment by dozoisch** [comment]
@invalidred Hmmm that's indeed a bit more complicated. One thing that could be done is that we could allow for a env variable to be set a build time by the users including it in their project. (eg process.env.LANG" or something like this. A lot of framework do that now (eg react needs process.env.NODE_ENV=production, same for redux etc.). But that wouldn't fix the language change... I guess even reCAPTCHA doesn't really handle the language change well.

They are supposed to render in the user preferred language though (from browser settings) so normally that shouldn't even be an issue.

I guess we could also use the other way of deleting the old script node, and recreating a new one on language change but that looks hacky and error prone :/

**Comment by invalidred** [comment]
It would be real nice to have languageCode specified as a parameter of the component rather than something users have to specify while building the component. I agree with the current setup deleting the old script node and recreating a new one on language change seems hacky, however changing languageCode should display recpatcha with new language is exactly what the user would expect. I am not sure how to accomplish this yet, however i will spend some time meditating on this and come up with possible solutions and let you know my findings. In the mean while if you have a good idea or any way i could contibute, please let me know.

**Comment by iranreyes** [comment]
I recently faced this issue and I need to resolve it in order to continue. I was thinking on this and the best idea is rewrite the way that the lib was implemented taking care of the current code. By now my idea of not breaking change is configure the language externally. It is a quirk temp solution while the next version is ready

```
const lang = (window.recaptchaOptions && window.recaptchaOptions.lang) 
                     ? '&hl=' + window.recaptchaOptions.lang 
                     : '';
const URL = `https://www.google.com/recaptcha/api.js?onload=${callbackName}&render=explicit${lang}`;
```
