### ISSUE TITLE
onExpired doesn't get called when using 'invisible' reCAPTCHA

### ISSUE THREAD

**Issue by mocantimoteidavid** [dozoisch/react-google-recaptcha#184]
react-google-recaptcha version: 2.1.0
react-async-script version: 1.1.1

In my usage of the Recaptcha component, when setting it to be `size="invisible"` and `badge="inline"`, it seems that the onExpired is never called.

```
handleSubmitOfForm = async () => {
  const token = await this.recaptchaRef.current?.executeAsync();
  await this.setState({ /* setting the token value */ });
}

<ReCAPTCHA
  ref={this.recaptchaRef}
  sitekey="key"
  size="invisible"
  badge="inline"
  onExpired={() => {
    this.setState({ /* clearing the token */ });
  }}
  onChange={token => {
    if (token) {
      this.setState({ /* setting the token value */ });
    }
  }}
/>
```

So after submitting the form (which gets a captcha token), the `onExpired` is never called. 
Is there any special behavior I'm missing with using the `'invisible'` captcha? Because on the normal one (without `size="invisible"`) `onExpired` works just fine.

**Comment by hartzis** [comment]
@mocantimoteidavid Thank you for the issue and explanation.  

Looking at the code, there isn't anything special we are doing for `invisible` in relation to `onExpired`.
https://github.com/dozoisch/react-google-recaptcha/blob/3ef5bc9df6ff6a08ea5c8f195d4c1be7a9ba56af/src/recaptcha.js#L90-L91

This has me thinking it is either a "bug" or something else with google recaptcha itself.

Docs for recaptcha - https://developers.google.com/recaptcha/docs/invisible
- they dont mention anything in relation to expired and invisible
- 🤔 i'm curious if `expired` is even possible for invisible since it is kind of validating a user in the background and there is nothing a user can do to trigger a re-verify if that makes sense

if you are still experiencing this could you create a codesandbox.io example that demonstrates this and we could at least start to narrow it down?

Cheers.

**Comment by TobiasWehrum** [comment]
I'm pretty new to using reCATPCHA, but from what I can see, reCAPTCHA v2 invisible is working for me at least as I expect it regarding onExpired:

- Once I trigger it with execute(), it will generate a token for me.
- Whenever retrigger execute() within the ~50 seconds expiration time, it will return the same token, since it is still valid.
- ~50 seconds after the first execute() generated a new token, that token will expire. onExpired() is called, and if I call execute() again, it will generate a new token which will again be valid for ~50 seconds.

**Comment by hartzis** [comment]
Closing this with the great insight @TobiasWehrum provided.
