### ISSUE TITLE
Execute doesn't work on invisible when recaptcha isn't cached

### ISSUE THREAD

**Issue by themirror178** [dozoisch/react-google-recaptcha#50]
I'm running execute on the ref returned by the callback to ReCAPTCHA. If it's the second time (i.e. cached), execute() works. If recaptcha hasn't been cached (e.g. first time in incognito), execute() does nothing.

After some analysis it seems to be because this.__executeRequested is undefined in explicitRender, even though it gets set in execute().... some kind of race condition?

Environment:
```
+-- react@15.6.1
+-- react-async-script@0.9.1
+-- react-dom@15.6.1
`-- react-google-recaptcha@0.9.6
```

**Comment by dozoisch** [comment]
Ah yes, there seems like there could be a race condition.  I'll try to look at it this week, unless you have time to figure it out and submit a PR.

**Comment by antoniotaha** [comment]
Any solution?

**Comment by aij** [comment]
I don't see how `_executeRequested` could ever go back to undefined.

@themirror178 Are you sure you're checking the same instance of `ReCAPTCHA`? Is it possible a re-render is destroying the instance where `.execute()` was called and creating a new instance where it hasn't been called yet?

`explicitRender()` is perhaps more confusing than necessary, since using `setState` will trigger a re-render, and `.execute()` will be deferred until that update. (Since after calling `setState`, `this.state` still has the old value.) It looks correct though because `componentDidUpdate()` will re-call `explicitRender` with the new state.

**Comment by themirror178** [comment]
@aij I haven't looked into this for a while, and have reverted to normal Recaptcha, but I was only had 1 instance of ReCAPTCHA at a time. I'll might have to look into Invisible in the coming weeks, so I'll look into this again then.

**Comment by sarneeh** [comment]
Hey! As I also encountered some issues with this lib and couldn't solve it in a clean way so I decided to create my own library. It has some improvements comparing to this and most important - it works completely fine! 🚀 And what's most awesome - it's more a React-way of doing things, without assigning variables outside the component. Check it out if you're interested 😄 

Library: https://github.com/sarneeh/reaptcha
Example: https://sarneeh.github.io/reaptcha/

**Comment by harrysoer** [comment]
I tried to reference the component and it seems working fine for me

    recaptchaRef:any;

    submitForm(e){
        e.preventDefault()
        this.recaptchaRef.execute()
    }

    render(){
        return(
            <form onSubmit={e=>this.submitForm}>
                <Recaptcha
                    sitekey="==YOUR-SITEKEY=="
                    ref={e => this.recaptchaRef = e}
                    onChange={token => this.props.verifyCaptcha(token)}
                    size={"invisible"}
               />
               <button class="btn btn-primary" type="submit" />
            </form>
       )
    }

**Comment by hartzis** [comment]
closing with update and 1.0.0 release. Please re-open if anyone is having an issue and include a codesandbox.io example if possible
