### ISSUE TITLE
 Error: ReCAPTCHA has already been rendered in this element when rendering page for second time

### ISSUE THREAD

**Issue by mdurban** [dozoisch/react-google-recaptcha#55]
If I render my page with the invisible captcha, everything works as expected. If leave the page (i.e. back-button) and come back to my page with the captcha, I get the error `Error: ReCAPTCHA has already been rendered in this element`.

I am trying to use the `captcha.reset()` function, but it doesn't seem to be doing what I expect. I have tried the `reset()` in multiple react lifecycle locations (componentWillMount, componentWillUnmount, render), but I'm still seeing the error.

I'm rendering the invisible captcha using this code:
```
render() {

return (
  <button className='confirm' onClick={() =>captcha.execute()}>
    <ReCAPTCHA
      className='recaptcha'
      ref={(element) => { captcha = element }}
      size='invisible'
      sitekey='__sitekey__'
      onChange={this.doConfirm}
    />
  <button>
)
}
```

**Comment by jhrdina** [comment]
The problem is that DOM generated by `this.props.grecaptcha.render()` is not removed during `<ReCAPTCHA`'s  unmount and therefore can cause trouble when rendering a new instance at the same place.

I can see two possible solutions:

1. Implement `componentWillUnmount` to do following:
    - Remove all DOM generated by `this.props.grecaptcha.render()` including the render target element. (we don't want to remove the div generated by React, so we probably want to manually add a wrapper div for this purpose)
    - Call `grecaptcha.reset(widgetId)` to do memory cleaning (as mentioned [here](https://stackoverflow.com/questions/45587315/removing-recaptcha-v2-problematically-after-being-solved) and [here](https://developers.google.com/recaptcha/docs/faq))
2. Detach rendered DOM inside `componentWillUnmount` and save it into some global variable for later reuse. This _prevents_ the component from _slow reloading_ after each use, however different instances may need different rendering parameters so this has to be taken into account.

**Comment by dozoisch** [comment]
@jhrdina yeah I think the first approach makes more sense. Would you have time to do a PR for this? I don't currently have a lot of bandwidth, but will be happy to review & release.
