### ISSUE TITLE
support for react v0.14-beta

### ISSUE THREAD

**Issue by nikshulipa** [dozoisch/react-google-recaptcha#9]
package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-google-recaptcha@0.4.0 wants react@>=0.13

but in package.json I have
"react": "0.14.0-beta2"

**Comment by dozoisch** [comment]
As of right now, I'm really in a rush. I'll try to find time test it with react-0.14 but I can't give an estimate. PRs are accepted.

**Comment by spicydonuts** [comment]
This PR updates the react peer dependency to `>=0.14.0`, meaning people wanting to keep using `0.13.x` will need to also not update `react-google-recaptcha`.  This is necessary because the API for accessing DOM nodes changed in `0.14.0` and the component will no longer work with prior versions of React.
